#pragma once
#include "MRKModel.h"
#include "MRKBuffer.h"
#include "MRKImage.h"

/*
 * The perspective projection matrix generated by GLM will use the OpenGL depth range of
 * -1.0 to 1.0 by default. We need to configure it to use the Vulkan range of 0.0 to 1.0
 * using the GLM_FORCE_DEPTH_ZERO_TO_ONE definition.
 * 
 * This is done in the Visual Studio pre-processor settings
 */
#include "MRKDescriptor.h"

namespace mrk
{
    enum class ShaderType;
    struct LoadResourcesCreateInfo;

    struct UniformBufferObject
    {
        glm::mat4 model; // Model to world
        glm::mat4 view;  // world to camera
        glm::mat4 proj;  // camera to ndc
    };

    class ResourceManager
    {
    public:
        struct loadInfo
        {
            loadInfo(char const* house_model_path, char const* house_model_texture_path)
                : houseModelPath(house_model_path),
                  houseModelTexturePath(house_model_texture_path)
            {
            }

            char const * const houseModelPath;
            char const * const houseModelTexturePath;
        };

        explicit ResourceManager() = default;
        ~ResourceManager();
        void load(LoadResourcesCreateInfo const & info);

        mrk::Descriptor const & getDescriptor() const;
        mrk::Buffer const & getUniformBuffer() const;
		mrk::Buffer const & getVertexBuffer() const;
		mrk::Buffer const & getIndexBuffer() const;
        std::vector<std::tuple<vk::ShaderModule, vk::ShaderStageFlagBits, char const *>> const & getShadersFromShaderType(ShaderType type);

    private:
        // Obviously this is NOT final. We will have an array of Models
        Model houseModel_; 
        mrk::Buffer houseVertexBuffer_;
        mrk::Buffer houseIndexBuffer_;
        mrk::Buffer houseUniformBuffer_;
        std::vector<mrk::Image> houseTextures_;
        mrk::Descriptor descriptor_;

        // ShaderType and all the shaders that associate with it
        std::unordered_map<ShaderType, std::vector< std::tuple<vk::ShaderModule, vk::ShaderStageFlagBits, char const *> > > shaderGroups;
        void setUpShaderGroups();

        static vk::ShaderModule loadShaderModule(char const * const shaderPath);
    };
}
